cursor #efe0d6
cursor_text_color #d6c3b6

foreground            #efe0d6
background            #19120c
selection_foreground  #412c19
selection_background  #e3c0a5
url_color             #ffb77b

color0   #19120c
color1   #ff756d
color2   #91ff7b
color3   #ffe56d
color4   #f2a05b
color5   #763805
color6   #ffb77b
color7   #fff6ef
color8   #46413d
color9   #ffa19c
color10  #b2ffa2
color11  #ffeea2
color12  #ffc18e
color13  #ffcca2
color14  #ffdec3
color15  #fffbf8
